### ISSUE TITLE
UnicodeDecodeError on install with pip

### ISSUE THREAD

**Issue by fedeoppi** [seomoz/reppy#106]
I'm getting this error on Windows10 when installing.

Using python 3.6.5

Any Idea on how to solve?

```Installing collected packages: reppy
  Running setup.py install for reppy ... error
Exception:
Traceback (most recent call last):
  File "c:\web\crowl\.venv\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 82: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\web\crowl\.venv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\web\crowl\.venv\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\web\crowl\.venv\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\web\crowl\.venv\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\web\crowl\.venv\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\web\crowl\.venv\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 82: invalid start byte```

**Comment by fedeoppi** [comment]
solved upgrading pip to 19.0.2
