### ISSUE TITLE
ValueError: Invalid time.

### ISSUE THREAD

**Issue by wilima** [seomoz/reppy#48]
Hello, I am getting this exception:

```
Could not parse date string -1
Traceback (most recent call last):
  File "/home/mikula/.virtualenvs/crawler/lib/python3.6/site-packages/reppy/ttl.py", line 60, in ttl
    return max(self.minimum, parse_date(expires) - date)
  File "/home/mikula/.virtualenvs/crawler/lib/python3.6/site-packages/reppy/util.py", line 11, in parse_date
    raise ValueError("Invalid time.")
ValueError: Invalid time.
```

**Comment by b4hand** [comment]
Can you please include the input and steps to reproduce this exception?

**Comment by wilima** [comment]
I am calling this lib from celery tasks in my worker, its really hard to reproduce it probably :/ I will try.

**Comment by wilima** [comment]
One more thing, is reppy thread/fork save? Because I am using reppy in Celery. I have global file with reppy and multiprocess locks like this: https://github.com/UPOLSearch/UPOL-Crawler/blob/development/crawler/urls/robots.py

**Comment by azotlikid** [comment]
Hello,

I have the same problem. It occurs with only a few robots.txt:

exception : 
```
Could not parse date string -1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/reppy/ttl.py", line 60, in ttl
    return max(self.minimum, parse_date(expires) - date)
  File "/usr/local/lib/python3.5/dist-packages/reppy/util.py", line 11, in parse_date
    raise ValueError("Invalid time.")
ValueError: Invalid time.
```
or :

```
Could not parse date string 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/reppy/ttl.py", line 60, in ttl
    return max(self.minimum, parse_date(expires) - date)
  File "/usr/local/lib/python3.5/dist-packages/reppy/util.py", line 11, in parse_date
    raise ValueError("Invalid time.")
ValueError: Invalid time.
```
examples : 

```
from reppy.robots import Robots

r = Robots.fetch('http://www.tripadvisor.fr/robots.txt')
r = Robots.fetch('https://www.udemy.com/robots.txt')
r = Robots.fetch('https://www.jamendo.com/robots.txt')
r = Robots.fetch('https://musopen.org/robots.txt')

```

I don't know if it's related but the response headers for all those files contains : 

`Cache-Control : "no-cache, no-store, max-age=0, must-revalidate "`

**Comment by b4hand** [comment]
Thanks for the reproducing case. This appears to be a very simple typo bug. PR coming.

**Comment by b4hand** [comment]
v0.4.4 has been pushed to pypi with a fix for this issue.
